version: '3'

services:
  # [ service "app" ]
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ../:/projects
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=pass
    links:
      - mongo

  # [ service "mongo" ]
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
