version: '3'

services:
  # [ service "app" ]
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  # [ service "db" ]
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: secret_board
      TZ: "Asia/Tokyo"
    volumes:
      - ../secret-board-db:/var/lib/postgresql/data
  # # [ service "password-challenger" ]
  # password-challenger:
  #   build: .
  #   tty: true
  #   volumes:
  #     - ../password-challenger:/app
  #   depends_on:
  #     - app