version: '3'

services:
  # [ service "app" ]
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  # [ service "db" ]
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedule_arranger